//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.29 at 09:30:02 午前 JST 
//


package nablarch.core.repository.di.config.xml.schema;



/**
 * <p>Java class for AutowireType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AutowireType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ByType"/>
 *     &lt;enumeration value="ByName"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum AutowireType {

    BY_TYPE("ByType"),
    BY_NAME("ByName"),
    NONE("None");
    private final String value;

    AutowireType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AutowireType fromValue(String v) {
        for (AutowireType c: AutowireType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
