//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.29 at 09:30:02 午前 JST 
//


package nablarch.core.repository.di.config.xml.schema;

import java.util.ArrayList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="import" type="{http://tis.co.jp/nablarch/component-configuration}Import" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="config-file" type="{http://tis.co.jp/nablarch/component-configuration}ConfigFile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="component" type="{http://tis.co.jp/nablarch/component-configuration}Component" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="list" type="{http://tis.co.jp/nablarch/component-configuration}List" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="map" type="{http://tis.co.jp/nablarch/component-configuration}Map" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class ComponentConfiguration {

    protected java.util.List<Object> importOrConfigFileOrComponent;

    /**
     * Gets the value of the importOrConfigFileOrComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importOrConfigFileOrComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportOrConfigFileOrComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link nablarch.core.repository.di.config.xml.schema.List }
     * {@link ConfigFile }
     * {@link Map }
     * {@link Component }
     * {@link Import }
     * 
     * 
     */
    public java.util.List<Object> getImportOrConfigFileOrComponent() {
        if (importOrConfigFileOrComponent == null) {
            importOrConfigFileOrComponent = new ArrayList<Object>();
        }
        return this.importOrConfigFileOrComponent;
    }

}
