//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.29 at 09:30:02 午前 JST 
//


package nablarch.core.repository.di.config.xml.schema;



/**
 * Mapのエントリを設定する型。
 * 
 * <p>Java class for Entry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="key-component" type="{http://tis.co.jp/nablarch/component-configuration}Component" minOccurs="0"/>
 *         &lt;element name="value-component" type="{http://tis.co.jp/nablarch/component-configuration}Component" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="key-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Entry {

    protected Component keyComponent;
    protected Component valueComponent;
    protected String key;
    protected String keyName;
    protected String value;
    protected String valueName;

    /**
     * Gets the value of the keyComponent property.
     * 
     * @return
     *     possible object is
     *     {@link Component }
     *     
     */
    public Component getKeyComponent() {
        return keyComponent;
    }

    /**
     * Sets the value of the keyComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Component }
     *     
     */
    public void setKeyComponent(Component value) {
        this.keyComponent = value;
    }

    /**
     * Gets the value of the valueComponent property.
     * 
     * @return
     *     possible object is
     *     {@link Component }
     *     
     */
    public Component getValueComponent() {
        return valueComponent;
    }

    /**
     * Sets the value of the valueComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Component }
     *     
     */
    public void setValueComponent(Component value) {
        this.valueComponent = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueName() {
        return valueName;
    }

    /**
     * Sets the value of the valueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueName(String value) {
        this.valueName = value;
    }

}
